[[news]]
date = "2025-04"
content = "共同第一作者论文“基于颅骨 CT 元数据和三维深度学习框架的自动骨龄评估”在线发表于 International Journal of Legal Medicine。"

[[news]]
date = "2025-02"
content = "第一作者论文“中国藏族双胞胎多种骨龄评估方法个案研究”发表于 Legal Medicine。"

[[news]]
date = "2024"
content = "第一作者论文“基于深度学习语义分割技术的气胸肺萎陷程度自动化计算”发表于《刑事技术》。"

[[news]]
date = "2023-09"
content = "第一作者论文“基于多层螺旋 CT 耻骨骨密度的成人年龄推断”发表于 International Journal of Legal Medicine。"
